services:
  ml-api:
    build:
      context: ./cotton-api
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"

  backend:
    build:
      context: ./cotton-api
      dockerfile: Dockerfile.node
    ports:
      - "5000:5000"
    depends_on:
      - ml-api

  frontend:
    build:
      context: ./cottoncore-digital-repository
    ports:
      - "3000:80"
    depends_on:
      - backend